export const Data = [
    {
        name: 'Taronga Zoo',
        address: 'Bradley\'s Head Rd, Mosman NSW 2088, Australia',
        description: 'Overlooking Sydney Harbour, Taronga Zoo is known for its stunning views and conservation efforts. It houses a diverse range of animals from around the world.',
        nearbyHotel: 'The Taronga Vista Apartments offer convenient accommodation.',
        rarestAnimal: 'Sumatran Tiger - Taronga Zoo participates in global breeding programs for Sumatran tigers, contributing to the conservation of this critically endangered species.',
        rarestAnimalPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAM4x-Noj78kZGjIZ9l2OyZbhGqscXTbze7_Ym1papQ&s',
        uri: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Aus_zoo_sign.jpg',
        zooAddress: { latitude: 12, longitude: -122 },
    },
    {
        name: 'Ocean Park Aquarium',
        address: 'Insert Ocean Park Aquarium Address Here',
        description: 'Insert Ocean Park Aquarium Description Here',
        nearbyHotel: 'Insert Nearby Hotel for Ocean Park Aquarium Here',
        rarestAnimal: 'Insert Rarest/Most Interesting Animal for Ocean Park Aquarium Here',
        rarestAnimalPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAM4x-Noj78kZGjIZ9l2OyZbhGqscXTbze7_Ym1papQ&s',
        uri: 'https://lh3.googleusercontent.com/p/AF1QipP-o3pbfvloDrusLj-lAC-5Us3KmC0QZaUVIXou=s1360-w1360-h1020',
        zooAddress: { latitude: 12, longitude: -122 },
    },
    {
        name: 'Perth Zoo',
        address: '20 Labouchere Rd, South Perth WA 6151, Australia',
        description: 'Perth Zoo, located along the Swan River, focuses on conservation and education. It has a variety of exhibits representing different regions and ecosystems.',
        nearbyHotel: 'The Peninsula Riverside Serviced Apartments offer proximity to Perth Zoo.',
        rarestAnimal: 'Western Swamp Tortoise - Perth Zoo is involved in the conservation efforts of the critically endangered Western Swamp Tortoise, a species native to Western Australia.',
        rarestAnimalPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAM4x-Noj78kZGjIZ9l2OyZbhGqscXTbze7_Ym1papQ&s',
        uri: 'https://lh3.googleusercontent.com/p/AF1QipMYUU5o-x00Pb-xEaoWtYPlvTC9uSlOAVAZ8i5B=s1360-w1360-h1020',
        zooAddress: { latitude: 12, longitude: -122 },
    },
    {
        name: 'Gorge Wildlife Park',
        address: 'Insert Gorge Wildlife Park Address Here',
        description: 'Insert Gorge Wildlife Park Description Here',
        nearbyHotel: 'Insert Nearby Hotel for Gorge Wildlife Park Here',
        rarestAnimal: 'Insert Rarest/Most Interesting Animal for Gorge Wildlife Park Here',
        rarestAnimalPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAM4x-Noj78kZGjIZ9l2OyZbhGqscXTbze7_Ym1papQ&s',
        uri: 'https://lh3.googleusercontent.com/p/AF1QipOw97nvU_9bF7Xq4dPdLpdxcD3HUrUnBq6WkZWb=s1360-w1360-h1020',
        zooAddress: { latitude: 12, longitude: -122 },
    },
    {
        name: 'Melbourne Zoo',
        address: 'Elliott Ave, Parkville VIC 3052, Australia',
        description: 'Established in 1862, Melbourne Zoo is one of the oldest zoos in the world. It features a wide variety of animals in naturalistic habitats.',
        nearbyHotel: 'The Larwill Studio provides a comfortable stay near Melbourne Zoo.',
        rarestAnimal: 'Snow Leopard - Melbourne Zoo is home to a majestic snow leopard, an endangered species known for its elusive nature and beautiful fur.',
        rarestAnimalPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAM4x-Noj78kZGjIZ9l2OyZbhGqscXTbze7_Ym1papQ&s',
        uri: 'https://lh3.googleusercontent.com/p/AF1QipM-PqpOq_RMGVfAbsmr6oCPNacbt1E4dFMsrXLE=s1360-w1360-h1020',
        zooAddress: { latitude: 12, longitude: -122 },
    },
    {
        name: 'Australia Zoo',
        address: '1638 Steve Irwin Way, Beerwah QLD 4519, Australia',
        description: 'Founded by Steve Irwin, Australia Zoo is renowned for its commitment to wildlife conservation. It offers interactive experiences and showcases a range of Australian and exotic animals.',
        nearbyHotel: 'Consider the Beerwah Motor Lodge for accommodation.',
        rarestAnimal: 'Cheetah - Australia Zoo is known for its cheetah breeding program, contributing to the conservation of these fast and endangered big cats.',
        rarestAnimalPhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZAM4x-Noj78kZGjIZ9l2OyZbhGqscXTbze7_Ym1papQ&s',
        uri: 'https://lh3.googleusercontent.com/p/AF1QipMFyY9g6tbwUSgDSoA2iueb8YW-G1p3SjyJJZJZ=s1360-w1360-h1020',
        zooAddress: { latitude: 12, longitude: -122 },
    },
];